remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Decoding the Draft - How Bans and Picks Influence Victory in League of Legends
description: This project will use the [2024 League of Legends eSports Match Data](https://drive.google.com/drive/u/1/folders/1gLSw0RLjBbtaNy0dgnGQDAZOHIgCe-HH) to analyze bans and picks in League of Legends. I aim to analyze the effectiveness and most optimal combos of champion bans and picks, and determine the extent of their effect on match behavior and outcome.
